### ISSUE TITLE
setting up and using PowerTasks against the Powershell default installation (ISE only, VS.NET not present)

### ISSUE THREAD

**Issue by sundmoon** [shaynevanasperen/PowerTasks#19]
Please add a couple of phrases to README.md on this case.

**Comment by shaynevanasperen** [comment]
Why don't you submit a pull request?

**Comment by sundmoon** [comment]
Hi

Unfortunately i lack skills yet to have done that in a reasonable timeframe.
I am slill looking for a "cheating" solution to start PS development with
CI\CD pipeline, close to be ready for use.


2016-12-12 16:51 GMT+03:00 Shayne van Asperen <notifications@github.com>:

**Comment by NReilingh** [comment]
I'm actually trying to figure this out now.

I installed PowerTasks by creating a packages.config file with PowerTasks and then running `nuget restore -PackagesDirectory packages`. So, now I've got the PowerTasks distribution folder, but the install.ps1 script did not run -- this appears to be a known limitation of CLI installs.

So, I can find the default .Tasks.ps1 file, but it looks like the install script would have modified and created pt.bat. I'm not entirely sure what parameters I'd need to supply to install.ps1 to run it with success manually, but I'm going to mess around with it a bit and see what I can figure out.

@shaynevanasperen Do you have any thoughts on the best solution to the problem of install.ps1 not being triggered outside of VS?

**Comment by shaynevanasperen** [comment]
@NReilingh Unfortunately I don't have a solution to the problem of install.ps1 not being triggered outside of VS. NuGet was not designed to be able to run install.ps1 or uninstall.ps1 outside of VS. See [here](http://stackoverflow.com/questions/6892025/nuget-install-ps1-does-not-get-called), [here](http://stackoverflow.com/questions/37973023/run-install-ps1-when-not-installing-in-visualstudio), and [here](http://codepyre.com/2012/10/nuget-youre-doing-it-wrong/) for more information.

Futhermore, since NuGet 3, support for solution level packages and mutable content files has been deprecated. See [here](http://blog.nuget.org/20151008/NuGet-3-What-and-Why.html) and [here](https://github.com/NuGet/Home/wiki/Bringing-back-content-support,-September-24th,-2015) for more information. In addition to this, with the new cross-platform vision of .NET Core, using Powershell for build automation is no longer the best choice because Powershell itself is not cross-platform.

Due to these developments, I've decided to abandon using Powershell for build automation and instead use [Cake (C# Make)](http://cakebuild.net/). Another alternative worth considering is [Fake (F# Make)](http://fsharp.github.io/FAKE/) which perhaps has more potential than Cake, although it's probably not as mature yet. My current plan is to just start using Cake as-is, without any meta-package or plugin system like I have for PowerTasks, and then after some time if I find myself writing a lot of the same boilerplate code repeatedly I might decide to create something similar. So far in my limited use of Cake, I've found it to be quite easy to learn and use, with very little boilerplate code, so I doubt it will even be necessary. Cake already has a very solid collection of built-in tasks as well as community based addins as you can see [here](http://cakebuild.net/dsl/) so I would encourage you to look into that, and if there is something missing that you need you can always contribute your own addin.

I'd also like to point you to this excellent blog article by Michael Whelan, titled [Continuous Delivery for .Net Core with GitHub, Cake, GitTools, and AppVeyor](http://www.michael-whelan.net/continuous-delivery-github-cake-gittools-appveyor/), which may give you some food for thought.

It would help to know what it is you are trying to achieve with PowerTasks. Perhaps it's worth taking a step back and re-evaluating what the best tool for the job is. It's always tricky to create something like this because it tends to be very opinionated, which limits it's usefulness outside of your specific use-case.

**Comment by NReilingh** [comment]
Thanks for this, @shaynevanasperen! To give some context, the area that I'm working in is actually database development for SQL Server. I don't work with C# at all -- it's all T-SQL and PowerShell -- and the problems I'm trying to solve are around devops automation and package management. PowerShell has gotten me pretty far on the devops front, and I really fell in love with Invoke-Build for managing those tasks. (By the way, haven't you heard that [PowerShell 6](https://github.com/powershell/powershell) is cross platform?)

The related package management issue has been a bit of a struggle with NuGet from the start. All I want to do is restore files to a packages directory and read them from Invoke-Build tasks... NuGet is supposedly the basis for the likes of PowerShellGet and Chocolatey, but at the same time seems practically unusable outside of a Visual Studio environment. Not sure if I'm supposed to invent my own NuGet-based package manager, or save a bootstrapping script to my repo with the one NuGet CLI command that does what I want against the (deprecated?) packages.config format.

Anyway I'm exploring PowerTasks because I want to modularize and re-use pieces of my Invoke-Build scripts. I really like the idea of leveraging NuGet for the plugin model.

**Comment by nightroman** [comment]
@NReilingh For package management of your own IB related NuGet packages I
would recommend [paket](https://fsprojects.github.io/Paket/index.html).

It is built with F# but you do not have to install, just get *paket.exe*.
It is like *NuGet.exe* but in some ways better. And it does not rely on VS.

I will use *PowerTasks.Plugins.Clean* just as an example.

You create your *paket.dependencies* file:

    source https://www.nuget.org/api/v2
    nuget PowerTasks.Plugins.Clean

Then you invoke

    paket install

It analyses the package dependencies, creates *paket.lock*

    NUGET
      remote: https://www.nuget.org/api/v2
        Invoke-Build (3.2.2)
        PowerTasks (3.1.1)
          Invoke-Build (>= 2.14.4)
        PowerTasks.Plugins.Clean (2.0)
          PowerTasks (>= 2.0)

and downloads the packages to the *packages* directory

    package
        Invoke-Build
        PowerTasks
        PowerTasks.Plugins.Clean

Note that unlike NuGet, it does not add version numbers to directory names.
As a result, after `paket` `install` or `restore` you can count on paths like
*packages\Invoke-Build\tools\Invoke-Build.ps1* (build engine itself) and paths
of task scripts from other packages to be imported into your build script.

This is not a perfect example but it gives the idea. You package your reusable
pieces with required dependencies, push them to NuGet, use them with `paket`
with required *paket.dependencies* for a particular project. In your build
script you import (dot-source or invoke) task scripts, e.g.

    . packages/PowerTasks.Plugins.Clean/scripts/Clean.ps1

**Comment by shaynevanasperen** [comment]
@nightroman That is a rather excellent suggestion. Thanks for your contribution. @NReilingh Thanks for the context. I'd recommend you follow the suggestion proposed by @nightroman. I didn't know that Powershell 6 will be cross-platform, that's good to know. Thanks for mentioning it.
